defaults:
  - _data_type_: gt

name: dsprites_imagenet_bg_80

data:
  _target_: research.code.dataset.data.DSpritesImagenetData
  visibility: 80
  mode: bg
  data_root: ${dsettings.storage.data_root}
  prepare: ${dsettings.dataset.prepare}
  in_memory: ${dsettings.dataset.try_in_memory}

transform:
  _target_: disent.dataset.transform.ToImgTensorF32
  mean: ${dataset.meta.vis_mean}
  std: ${dataset.meta.vis_std}

meta:
  x_shape: [3, 64, 64]
  vis_mean: [0.40867981393820857, 0.38468564002021527, 0.34611573047508204]
  vis_std: [0.22048328737091344, 0.22102216869942384, 0.22692977053753477]
