defaults:
  - _data_type_: gt

name: dsprites_imagenet_bg_20

data:
  _target_: disent.dataset.data.DSpritesImagenetData
  visibility: 20
  mode: bg
  data_root: ${dsettings.storage.data_root}
  prepare: ${dsettings.dataset.prepare}
  in_memory: ${dsettings.dataset.try_in_memory}

transform:
  _target_: disent.dataset.transform.ToImgTensorF32
  mean: ${dataset.meta.vis_mean}
  std: ${dataset.meta.vis_std}

meta:
  x_shape: [3, 64, 64]
  vis_mean: [0.13294969414492142, 0.12694375140936273, 0.11733572285575933]
  vis_std: [0.18311250427586276, 0.1840916474752131, 0.18607373519458442]
