defaults:
  - _input_mode_: weak_pair

name: augpos_tvae_os

cfg:
  _target_: research.code.frameworks.vae.AugPosTripletVae.cfg
  # base ae
  recon_loss: ${settings.framework.recon_loss}
  loss_reduction: ${settings.framework.loss_reduction}
  # base vae
  latent_distribution: ${settings.framework_opt.latent_distribution}
  # disable various components
  detach_decoder: FALSE
  disable_reg_loss: FALSE
  disable_rec_loss: FALSE
  disable_aug_loss: FALSE
  disable_posterior_scale: NULL
  # Beta-VAE
  beta: ${settings.framework.beta}
  # tvae: triplet stuffs
  triplet_loss: triplet
  triplet_margin_min: 0.001
  triplet_margin_max: 1
  triplet_scale: 0.1
  triplet_p: 1
  # overlap
  overlap_augment:
    _target_: disent.transform.FftBoxBlur
    p: 1.0
    radius: [ 16, 16 ]
    random_mode: "batch"
    random_same_xy: TRUE

  # TODO: try original
  # overlap_augment:
    # size = a_x.shape[2:4]
    # self._augment = torchvision.transforms.RandomOrder([
    #     kornia.augmentation.ColorJitter(brightness=0.25, contrast=0.25, saturation=0, hue=0.15),
    #     kornia.augmentation.RandomCrop(size=size, padding=8),
    #     # kornia.augmentation.RandomPerspective(distortion_scale=0.05, p=1.0),
    #     # kornia.augmentation.RandomRotation(degrees=4),
    # ])

meta:
  model_z_multiplier: 2
