defaults:
  - _input_mode_: triplet

name: tgadavae

cfg:
  _target_: research.code.frameworks.vae.TripletGuidedAdaVae.cfg
  # base ae
  recon_loss: ${settings.framework.recon_loss}
  loss_reduction: ${settings.framework.loss_reduction}
  # base vae
  latent_distribution: ${settings.framework_opt.latent_distribution}
  # disable various components
  detach_decoder: FALSE
  disable_reg_loss: FALSE
  disable_rec_loss: FALSE
  disable_aug_loss: FALSE
  disable_posterior_scale: NULL
  # Beta-VAE
  beta: ${settings.framework.beta}
  # adavae
  ada_average_mode: gvae  # gvae or ml-vae
  ada_thresh_mode: symmetric_kl
  ada_thresh_ratio: 0.5
  # guided adavae
  gada_anchor_ave_mode: 'average' # [average, thresh]
  # tvae: triplet stuffs
  triplet_loss: triplet
  triplet_margin_min: 0.001
  triplet_margin_max: 1
  triplet_scale: 0.1
  triplet_p: 1

meta:
  model_z_multiplier: 2
