# @package _global_

dsettings:
  trainer:
    cuda: NULL  # auto-detect cuda, some nodes are not configured correctly
  storage:
    logs_dir: 'logs'
    data_root: '/tmp/${oc.env:USER}/datasets'
  dataset:
    prepare: TRUE
    try_in_memory: TRUE
  launcher:
    partition: stampede
    array_parallelism: 16
    exclude: "mscluster93,mscluster94,mscluster97,mscluster99"

datamodule:
  gpu_augment: FALSE
  prepare_data_per_node: TRUE
  dataloader:
    num_workers: 16
    pin_memory: ${dsettings.trainer.cuda}
    batch_size: ${settings.dataset.batch_size}

hydra:
  job:
    name: 'disent'
  run:
    dir: '${dsettings.storage.logs_dir}/hydra_run/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.name}'
  sweep:
    dir: '${dsettings.storage.logs_dir}/hydra_sweep/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.name}'
    subdir: '${hydra.job.id}' # hydra.job.id is not available for dir
