defaults:
  - _input_mode_: triplet

name: adatvae

cfg:
  _target_: disent.frameworks.vae.experimental.AdaTripletVae.cfg
  # base ae
  recon_loss: ${settings.framework.recon_loss}
  loss_reduction: ${settings.framework.loss_reduction}
  # base vae
  latent_distribution: ${settings.framework_opt.latent_distribution}
  # disable various components
  disable_decoder: FALSE
  disable_reg_loss: FALSE
  disable_rec_loss: FALSE
  disable_aug_loss: FALSE
  disable_posterior_scale: NULL
  # Beta-VAE
  beta: ${settings.framework.beta}
  # tvae: triplet stuffs
  triplet_loss: triplet
  triplet_margin_min: 0.001
  triplet_margin_max: 1
  triplet_scale: 0.1
  triplet_p: 1
  # adavae
  ada_average_mode: gvae
  ada_thresh_mode: symmetric_kl  # Only works for: adat_share_mask_mode == "posterior" --- kl, symmetric_kl, dist, sampled_dist
  ada_thresh_ratio: 0.5          # >> USE WITH A SCHEDULE <<
  # ada_tvae - loss
  adat_triplet_loss: triplet_soft_ave_all
  adat_triplet_ratio: 1.0        # >> USE WITH A SCHEDULE << 0.5 is half of triplet and ada-triplet, 1.0 is all ada-triplet
  adat_triplet_soft_scale: 1.0   # >> USE WITH A SCHEDULE <<
  adat_triplet_pull_weight: 0.1  # Only works for: adat_triplet_loss == "triplet_hard_neg_ave_pull"
  adat_triplet_share_scale: 0.95  # >> USE WITH A SCHEDULE << only works for: adat_triplet_loss == "triplet_hard_neg_ave_scaled"
  # ada_tvae - averaging
  adat_share_mask_mode: posterior
  adat_share_ave_mode: all       # Only works for: adat_triplet_loss == "triplet_hard_ave_all"

meta:
  model_z_multiplier: 2
